version: "3.1"
services:
##################################################
#                   REDIS                        #
##################################################
    redis:
      image: redis:alpine
      container_name: redis
      restart: always
      ports:
        - "6379:6379"
      networks:
        - app-network 
##################################################
#                 PHPMYADMIN                     #
##################################################
    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      container_name: phpmyadmin 
      restart: always
      ports:
        - "8081:80"
      environment:
        - PMA_ARBITRARY=1
      networks:
        - app-network
      depends_on:
        - "mysql"
##################################################
#                 MYSQL                          #
##################################################
    mysql:
      image: mysql:5.7
      container_name: mysql
      working_dir: /application
      restart: always
      volumes:
        - ./.docker/dbdata:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=Moderador12@
        - MYSQL_DATABASE=cidadao_db
        - MYSQL_USER=deputado_honesto
        - MYSQL_PASSWORD=Moderador12@
      ports:
        - "3306:3306"
      networks:
        - app-network
##################################################
#                 NGINX                          #
##################################################
    nginx:
      image: nginx:1.17.4-alpine
      container_name: nginx
      restart: always
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./back-end:/application
      ports:
       - "8080:80"
      networks:
        - app-network
      depends_on:
        - "mysql"
        - "php-fpm"
##################################################
#                 PHP-FPM                        #
##################################################
    php-fpm:
      image: wesleyvieira12/cidadao-php-fpm:v1
      container_name: php-fpm
      working_dir: /application
      volumes:
        - ./back-end:/application
      restart: always
      networks:
        - app-network
      depends_on:
        - "mysql"
        - "redis"
##################################################
#                 SUPERVISOR                     #
##################################################
    supervisor:
      image: wesleyvieira12/cidadao-supervisor:v1
      container_name: supervisor
      working_dir: /application
      volumes:
        - ./back-end:/application
      restart: always
      ports:
        - "9001:9001"
      networks:
        - app-network
      depends_on:
        - "mysql"
        - "redis"
##################################################
#              REDES DOCKER                      #
##################################################
networks:
  app-network:
    driver: bridge
